import process, { argv } from "process";
import { parse } from "./parse.mjs";
import fs from "fs";
import path from "node:path";
import glob from "glob";
import { sleep } from "suzufunctions";
import { createRequire } from "module";
const require = createRequire(import.meta.url);
const config = require("./suzuconfig.json");

var inputFilesDir = "";
var outputFileDir = "";
var inputFiles = [];

async function interpret() {
    for (let i = 0; process.argv.length; i++) {
        if (argv[i] === "--input") inputFilesDir = argv[i + 1];
        if (argv[i] === "--output") outputFileDir = argv[i + 1];
        if (argv[i] === "--setup") {
            setup();
            process.exit(1);
        }
    
        if (argv[i] === "--help") {
            help();
            process.exit(1);
        }
        if (!process.argv[i]) break;
        if (inputFilesDir && outputFileDir) break;
    }
    
    console.log("Starting interpretor..., this might take a while...");
    
    if(!inputFilesDir) inputFilesDir = config.inputDir;
    if(!outputFileDir) outputFileDir = config.outputDir;
    
    if ((!inputFilesDir || !outputFileDir)) {
        console.log("No input or output file specified (Specify them by --input (folderPath) and --output (folderPath)");
        process.exit(1);
    }
    
    await glob(inputFilesDir + "**/*.suzu", function (er, files) {
        inputFiles = files;
    });
    
    while (inputFiles.length === 0) {
        await sleep(100);
    }
    for (let i = 0; i < inputFiles.length; i++) {
    
        var filePath = path.dirname(inputFiles[i]) + "/" + path.basename(inputFiles[i]).replace(".suzu", "") + `.mjs`;
    
        filePath = filePath.replace(`${inputFilesDir}`, `${outputFileDir}`);
    
        parse(`${inputFiles[i]}`, filePath, config.usestrict);
    }
    
    console.log("Finished!");
    process.exit(1);
    
    
    function setup() {
        console.log("Setting up...");
        console.log("Base file input and output directories are going to be : ./src/ and ./dist/");
    
        if (!fs.existsSync("./src")) fs.mkdirSync("./src");
        if (!fs.existsSync("./dist")) fs.mkdirSync("./dist");
    
        fs.writeFileSync("./src/index.suzu", "//?When running the starter program, run npm run start since windows need to be ran as qode in the package.json//? (To read this, turn on word wrap. You can just get rid of this) this file has automatically been generated by the suzu interpretor!\n//!Currently the language is WIP so some things might not work!\n//?The modifications so far is that you need to specify variable types, requires semicolons, and the code can auto generate a window, mineflayer bot, and discord client for you\n//?If you are wondering about variable names, first label created by label() is named label (Label takes 3 arguments for the rest, text, css, and then name), window from window() is named win, takes 2 inputs (width, heigh)\n //?Mineflayer bot is called bot created by createbot() (6 arguments, username, password, auth, host, version, and then if you are running the sbdoggos bot put true, otherwise false), and discord client is called client (takes 1 argument, token).\n//?Because it doesnt have a extension yet, my code will not have autocompletion, but if you are worried that something doesnt work just do it in javascript, the code will send the base code into the mjs files in the end if it is not recognised. If you want to use base js, type in 'use js' on the first line. You can import stuff while typing in .suzu, it auto replaces to .mjs, have fun!\nwindow(200, 600);\nlabel('Hello world!');");
    
        fs.writeFileSync("./src/bots.suzu", "//!The createClient will not work if you do not put in a token...\n//?If you want information on the laguage got to ./index.suzu or do node . --help\ncreateBot('', '', '', '', '', false);\ncreateClient('token');\n");
        console.log("Done setting up!");
    }
    
    function help() {
        console.log("Currently the language is WIP so some things might not work!\n?The modifications so far is that you need to specify variable types, requires semicolons, and the code can auto generate a window, mineflayer bot, and discord client for you\n?If you are wondering about variable names, first label created by label() is named label (Label takes 3 arguments for the rest, text, css, and then name), window from window() is named win, takes 2 inputs (width, heigh)\n ?Mineflayer bot is called bot created by createbot() (6 arguments, username, password, auth, host, version, and then if you are running the sbdoggos bot put true, otherwise false), and discord client is called client (takes 1 argument, token).\n?Because it doesnt have a extension yet, my code will not have autocompletion, but if you are worried that something doesnt work just do it in javascript, the code will send the base code into the mjs files in the end if it is not recognised. If you want to use base js, type in 'use js' on the first line. You can import stuff while typing in .suzu, it auto replaces to .mjs, have fun!");
    }
}

export { interpret as main };